@section('css')
<style>
    #educationCarousel {
        width: 100%;
    }

    #educationIndicators {
        margin: 0;
        gap: 6px;
    }

    #educationIndicators button {
        width: 20px;
        height: 20px;
        margin: 0;
        border: 0;
        border-radius: 50%;
        background-color: #adb5bd;
        opacity: 1;
    }

    #educationIndicators button.active {
        background-color: #212529;
    }

    @media (max-width: 499.98px) {
        #educationCarousel {
            padding: 0;
        }

        #educationCarousel .carousel-inner,
        #educationCarousel .carousel-item {
            width: 100%;
        }

        #educationCarousel .carousel-item .row {
            margin: 0;
            padding: 0 !important;

            --bs-gutter-x: 0;
        }

        #educationCarousel .carousel-item .col-12 {
            width: 100%;
            padding: 0;
        }

        #educationCarousel .education-item {
            width: 100%;
        }
    }
</style>
@endsection

<section id="education" class="d-flex flex-column gap-1">

    <div class="d-flex justify-content-between align-items-center">
        <h3 class="fw-bold text-sm-center text-lg-start">Education</h3>

        <button class="btn btn-primary" id="addEducation" type="button">
            <i class="fa-solid fa-plus me-1"></i>
            Add Education
        </button>
    </div>

    <hr>

    <div id="educationCarousel" class="carousel slide" data-bs-interval="false" data-bs-touch="true">
        <div class="carousel-inner" id="educationList">
            <!-- Generated by JS -->
        </div>
        <!-- Dot navigation -->
        <div class="carousel-indicators position-static mt-3" id="educationIndicators">
        </div>
    </div>

</section>

<x-modals.education-modal />

@push('scripts')
<script>
    document.addEventListener("DOMContentLoaded", function () {

        let listIOfFieldOfStudies = []
        let listIOfQualifications = []
        let educationModalEl = document.getElementById("educationModal");
        let educationModal = bootstrap.Modal.getOrCreateInstance(educationModalEl);
        let educationData = [];

        function renderEducationIndicators(totalSlides) {
            let $indicators = $("#educationIndicators");
            $indicators.empty();
            if (totalSlides <= 1) {
                $indicators.hide();
                return;
            }

            $indicators.show();
            for (let i = 0; i < totalSlides; i++) {

                let $dot = $("<button>").attr({
                        type: "button",
                        "data-bs-target": "#educationCarousel",
                        "data-bs-slide-to": i,
                        "aria-label": `Slide ${i + 1}`
                    });

                if (i === 0)
                    $dot.addClass("active").attr("aria-current", "true");

                $indicators.append($dot);
            }
        }

        function getEducationItemsPerSlide() {
            return $("#educationCarousel").width() < 600 ? 1 : 2;
        }
        // Get Data
        function getAllFieldOfStudies() {
            $.ajax({
                url: "{{ route('education.getAllFieldOfStudies') }}",
                type: "GET",
                dataType: "json",
                success: function ({ data }) {
                    console.log(data);
                    listIOfFieldOfStudies = data
                },
                error: function (xhr) {
                    console.error(xhr);
                }
            });
        }

        function getAllQualifications() {
            $.ajax({
                url: "{{ route('education.getAllQualifications') }}",
                type: "GET",
                dataType: "json",
                success: function ({ data }) {
                    console.log(data);
                    listIOfQualifications = data
                },
                error: function (xhr) {
                    console.error(xhr);
                }
            });
        }

        function getEducationDetail(eduId) {
            let url = "{{ route('education.getEducationById', ['id' => '__ID__']) }}";
            url = url.replace('__ID__', eduId);

            $.ajax({
                url: url,
                type: "GET",
                dataType: "json",

                success: function ({ data }) {
                    console.log(data);

                    $("#educationId").val(data.id);
                    $("#qualification").val(data.qualification_id);
                    $("#fieldOfStudy").val(data.field_of_study_id);
                    $("#cgpa").val(data.cgpa);
                    $("#startDate").val(data.start_date);
                    $("#endDate").val(data.end_date);
                    $("#description").val(data.description);
                    $("#enrollmentStatus").val(data.enrollment_status);

                    educationModal.show();
                },

                error: function (xhr) {
                    console.error(xhr);
                }
            });
        }
        // Get Data

        // Render
        function renderCardEducation(data, $educationList) {
            $educationList.empty();
            let itemsPerSlide = getEducationItemsPerSlide();

            let totalSlides = Math.ceil(data.length / itemsPerSlide);

            renderEducationIndicators(totalSlides);
            for (let i = 0;i < data.length;i += itemsPerSlide) {

                let educationGroup = data.slice(i,i + itemsPerSlide);

                let $carouselItem = $("<div>").addClass("carousel-item")
                    .toggleClass("active", i === 0);

                let $row = $("<div>").addClass("row g-3 px-3");

                educationGroup.forEach(education => {

                    let startDate = new Date(
                        education.start_date
                    ).toLocaleDateString("en-MY", {
                        month: "short",
                        year: "numeric"
                    });

                    let endDate = education.end_date ?
                        new Date(education.end_date).toLocaleDateString("en-MY", {
                            month: "short",
                            year: "numeric"
                        }) : "Present";

                    let columnClass = itemsPerSlide === 1 ? "col-12" : "col-6";
                    let $column = $("<div>").addClass(columnClass);
                    $column.html(`
                        <article
                            class="education-item h-100 border rounded-3 p-3 position-relative">

                            <button type="button"
                                id =
                                class="btn btn-secondary icon btn-edit-education position-absolute top-0 end-0 m-2"
                                data-id="${education.id}">
                                <i class="fa-solid fa-pencil"></i>
                            </button>

                            <div class="pe-4">
                                <p class="h5 fw-bold mb-2">
                                    Universiti Teknikal Malaysia
                                    Melaka (UTeM)
                                </p>
                                <p class="mb-1">
                                    ${education.qualification?.name ?? ""}
                                </p>
                                <p class="mb-1">
                                    ${education.field_of_study?.name ?? ""}
                                </p>
                                <p class="text-muted mb-2">
                                    ${startDate} - ${endDate}
                                </p>
                                <p class="mb-2">
                                    Grade: ${education.cgpa ?? "-"}
                                </p>
                                <p class="mb-2">
                                    ${education.description ?? ""}
                                </p>
                                <div class="d-flex gap-2 flex-wrap">
                                    ${education.enrollment_status ? `
                                        <span class="badge text-bg-primary">
                                            ${education.enrollment_status}
                                        </span>
                                    ` : ""}
                                    ${education.verification_status ? `
                                        <span class="badge text-bg-success">
                                            ${education.verification_status}
                                        </span>
                                    ` : ""}
                                </div>
                            </div>
                        </article>`);

                    $row.append($column);
                });

                $carouselItem.append($row);
                $educationList.append($carouselItem);
            }
        }
        function renderEmptyCardEducation($educationList) {
            $("#educationIndicators").hide();

            $educationList.html(`
                <div class="carousel-item active">
                    <p class="text-muted text-center py-5 mb-0">
                    No education added yet</p>
                </div>`);
        }

        function renderLoading($educationList) {
            $("#educationIndicators").hide();

            $educationList.html(`
                <div class="carousel-item active">
                    <div class="py-5 text-center">
                        <div
                            class="spinner-border"
                            role="status">
                        </div>
                        <p class="text-muted mt-2 mb-0">
                            Loading education...
                        </p>
                    </div>
                </div>
            `);
        }
        // Render

        // Load
        function loadEducations() {
            let $educationList = $("#educationList");
            renderLoading($educationList);

            $.ajax({
                url: "{{ route('education.getEducationByUserProfileId', ['id' => auth()->id()]) }}",
                type: "GET",
                dataType: "json",

                success: function ({ data }) {

                    if (!data || data.length === 0) {
                        educationData = [];
                        renderEmptyCardEducation($educationList);
                        return;
                    }

                    educationData = data;
                    renderCardEducation(educationData,$educationList);
                },

                error: function (xhr) {
                    console.error(xhr);
                }
            });
        }
        // Load

        // trigger

        $(".profile-tab[data-target='education']").on("click", function () {
            if (listIOfFieldOfStudies.length === 0 || listIOfQualifications.length === 0) {
                getAllFieldOfStudies();
                getAllQualifications();
            }
            loadEducations();
        });
        // trigger

        let resizeTimer;
        $(window).on("resize", function () {
            clearTimeout(resizeTimer);
            resizeTimer = setTimeout(function () {
                if (educationData.length === 0) return;
                renderCardEducation(educationData, $("#educationList"));
            }, 200);
        });

    })

</script>
@endpush
